/* Main.c file generated by New Project wizard
 *
 * Created:   Tue Sep 7 2021
 * Processor: STM32F103C6
 * Compiler:  Keil for ARM
 */

#include <stm32f1xx.h>
#include<main.h>
#include <keypadScan.h>
#include <lcd.h>
#include "MEF.h"
#include "seos.h"
#include "timer.h"

uint8_t a ;

int main (void)
 { 
    //4 indica Entrada de Alta Impedancia.
    //3 Indica Salida
    //8 Indica Entrada
       
     /* Enable clocks for GPIO ports => DO NOT DELETE*/
    RCC->APB2ENR |= 0xFC;       

    
    //Inicializar perif?ricos	
	KEYPAD_Init();
	LCDinit();	
	//Inicializar MEF	
	MEF_Init(10);	
	//Inicializar Timer (para el reloj)
	TIMER_Init((uint8_t)14,(uint8_t)59,(uint8_t)01);	
	//TIMER_Init(1,58,58);

	//Configurar Arq time-triggered
	//La libreria interrumpe cada xxms
	SEOS_Init();	
	
	//Habilitar interrupciones
	 //__enable_irq();	//Habilitamos las interrupciones globales
	 //__disable_irq();	//Deshabilitamos las interrupciones globales 
    
    
    
   while (1){ 
      SEOS_Dispatch_Tasks();
       testing_timer();
       delay_ms(4);
      
      }
 }   
